# This is the internal shell command used to pass 'native' commands to knapsack.
# It simply forwards the entire command line to knapsack, waits for a response, 
# And prints the response back to the user.
#
# Do not edit this file, it is dynamically generated each time knapsack runs.

if [ -z $KNAPSACK_PORT ]; then
	echo "KNAPSACK_PORT must be set."
	exit 1
fi

echo "`basename $0` $@" | $COMMAND 127.0.0.1 $KNAPSACK_PORT
